### ISSUE TITLE
Missing Gateway function?

### ISSUE THREAD

**Issue by ellimondo** [RootStudio/Root-Perch-Shop-Omnipay-v3#1]
Hi

Thanks for all your hard work on updating this. I've finally got around to testing it.

It's probably me, but is there a missing /runtime/gateways.php update in this repo? There's only 'stripe' and 'braintree' listed in the switch statement.

`perch_shop_payment_form('stripe_intents');` returns nothing - not even a missing template in the error log.

Also would you be kind enough to confirm where the `perch_stripe_checkout.js` call should go in the new checkout process?

**Comment by byron-roots** [comment]
Thanks for pointing that out, I've added the missing files now.

The `perch_stripe_checkout.js` call is replacing the the previous stipe V2 call. You'll now need to create your own payment form using [stipe elements](https://stripe.com/docs/stripe-js) to replace the old popup form that Stripe V2 would provide.
