### ISSUE TITLE
Support for Alipay

### ISSUE THREAD

**Issue by stephenturvey** [RootStudio/Root-Perch-Shop-Omnipay-v3#12]
Hi there, I've successfully integrated this so all is working fine but my client is asking about adding support for Alipay as they have a lot of Chinese customers.

According to the Stripe docs it's a case of adding alipay to the payment method types:

`payment_method_types: ['card', 'alipay']`

https://stripe.com/docs/payments/alipay/accept-a-payment?platform=checkout

However I can't find this checkout session code anywhere so just wondering if this is possible. Thanks

**Comment by byron-roots** [comment]
The payment method types option appears to be for stripe checkout, which is stripes hosted payment form. This gateway uses the stripe payment intents, so adding the option will have no effect.

The documentation does explain how to add Alipay to the intents method, so I'll look into the implementation process and see if it's possible through omnipay

**Comment by stephenturvey** [comment]
Thank you!

**Comment by stephenturvey** [comment]
Hi Byron, don't suppose you got a chance to look at this?

**Comment by byron-roots** [comment]
HI Stephen,

I haven't had time to work on this yet, though I have gone through the documentation and have a good idea on what I need to do. I'll be doing some other work with SCA so I should be able to get something out sometime next week.

For the most part I think it's frontend work with connecting alipay to stripe elements, and I'll just need to add some config options that will let you pass through some extra options. 

I won't be able to fully test this out for you as I've not used alipay in the past, and will unlikely use it anytime soon, but I'll do my best to help support it.

**Comment by stephenturvey** [comment]
That's great, much appreciated indeed. I'll check back in a week or two! Thank you

**Comment by stephenturvey** [comment]
Hi Byron, just checking back in, take it you haven't had chance to look yet?

**Comment by byron-roots** [comment]
Hi Stephen,

Apologies I didn't have time in the end to have a good look or make any changes. I did go through the documentation and it might be something that doesn't require any changes. I've not used Alipay before, btu hopefully the bellow should help

Here is the documentation for configuring the[ payments for Alipay](https://stripe.com/docs/payments/alipay/accept-a-payment?platform=web#handle-redirect), it looks to be a bit of front end and back end code. 

For Step 2 you should be able to add the ` 'payment_method_types' => ['alipay'] `straight into `perch_shop_checkout` function, as this should pass through any additional params 
```
perch_shop_checkout('stripe_intents', [
        'return_url' => PERCH_SHOP_COMPLETE,
        'cancel_url' => PERCH_SHOP_COMPLETE,
        'payment_method'      => perch_post('paymentMethodID'),
        'payment_method_types' => ['alipay', 'card'], // Card allows for normal stripe transactions
        'confirm' => true, // Tell the gateway to confirm the gateway. Require, if you leave this out the intents gateway won't work!
    ]);
```

You then just need to update your JS to that shown in step 3, and hopefully it should work.

**Comment by stephenturvey** [comment]
Thanks Byron, I'll give this a go and report back.
