### ISSUE TITLE
Orders registering in Perch admin but Result page showing payment not complete

### ISSUE THREAD

**Issue by ghost** [RootStudio/Root-Perch-Shop-Omnipay-v3#13]
Hello there, Thanks for all your work on this. 
I'm really close to this working. I've got to the point where the test payments are working completely both normal and authenticated but going to live with a real card, the result is showing 'payment not complete' even though the payment is going through and the order registering in Perch admin. It's like `perch_shop_order_successful()` is not firing on the result page.

I'm doing this on the checkout page:

```	
$return_url = 'https://xxxxxx.org.uk/shop/order-complete';
	$cancel_url = 'https://xxxxxx.org.uk/shop/order-complete';

/**
 * Check if the paymentMethodID has been posted from the form
 *
 * Also want to double check that the customer can complete the order
 */
if (perch_member_logged_in() && perch_post('paymentMethodID')) {

    /**
     * We use the stripe_intents Gateway here, instead of stripe.
     */
    perch_shop_checkout('stripe_intents', [
		'return_url' => $return_url,
		'cancel_url' => $cancel_url,
        'payment_method' => perch_post('paymentMethodID'), // Pass the payment method to the gateway
        'confirm'        => true, // Tell the gateway to confirm the gateway. Required, if you leave this out the intents gateway won't work!
    ]);
    
}
```

Then this on the result page:
```
<?php	

/**
 * Here we check if the payment was redirected or not. If the payment_intent field exists we need to finish the payment
 */
if (PerchUtil::get('payment_intent')) {

    $payment_opts = [
        'paymentIntentReference' => PerchUtil::get('payment_intent'), // set the reference ID
        'returnUrl'              => 'https://xxxxxx.org.uk/shop/order-complete',
        'confirm'                => true, // We are confirming the payment so we want this true
    ];

    // New method to confirm the payment. Use the above options and the new intents gateway
    perch_shop_confirm_payment('stripe_intents', $payment_opts);
}

// Rest of the page should be you success/unsuccessful order page
	perch_shop_complete_payment('stripe_intents');
	
	
	If(perch_shop_order_successful()){
		
			$giftAid = perch_shop_get_cart_property('gift_aid');
			PerchSystem::set_var('giftAid', $giftAid); 	
			
			$seatNum = perch_shop_get_cart_property('number_of_seats');
			PerchSystem::set_var('seatNum', $seatNum); 		

		    // Store the details of the order to variable>> Uses template orders>items.html
		    $orderSuccess = perch_shop_order_items(perch_shop_successful_order_id(), ['return-html' => true,'skip-template' => true]);
		    
		    
		    perch_shop_set_cart_property('terms_agreed', null);
	
		    perch_shop_empty_cart();
		    
		    perch_member_log_out();
	    
	}	
	
	perch_layout('global/shop.header', [
		'body-class' => 'result',
	]);
	
	perch_layout('global/nav.logo');

	echo '<div id="content_bg">';
    echo '<div id="container-content">';
	echo '<h1 class="link_hdr">';
	
	If(perch_shop_order_successful()){
	   		perch_pages_title(); 
	   }else{
	   		echo 'Payment Not Complete';
	} 
	
	echo '</h1><div class="result-wrapper">';
	
	


	// Has the order been succcessfully placed?
	if (perch_shop_order_successful()) {
		
	    // Yes! Show a success message
	    perch_content('Order successful');
	    
	    // Output the details of the order to the page>> Uses template orders>items.html
		
		echo $orderSuccess['html'];
	    
	}else{
	    
	    // Payment problem! Show instructions to the customer
	    perch_content('Payment not successful');
	}
?>
	</div>
    </div> <!--container-content end -->
    </div>   <!--content_bg end -->
<?php
    perch_layout('global/global.footer', [
		'footer-class' => 'checkout',	
    ]);
?>
```

Does `perch_shop_complete_payment('stripe_intents');` do anything? I didn't have it on the page but saw it in another thread on here but it doesn't seem to make a difference.

Any help greatly appreciated.

**Comment by byron-roots** [comment]
The `perch_shop_complete_payment('stripe_intents')` isn't required here as the Stripe gateway uses the confirmation process, I believe this is used with paypal and worldpay though.

Everything looks fine from what you have provided, are you getting any errors in your stripe logs? Would be worth double checking your stripe api keys are set correctly

**Comment by ghost** [comment]
Okay, thank you, that's really helpful.

That's what I thought re: perch_shop_complete_payment.

I'll have a look at the logs and keys. 

It's so difficult when the error is intermittent.

**Comment by ghost** [comment]
Okay I had a look thro the Stripe logs and nothing untoward there. Keys fine. 

I had another quick test of the result page and noticed a difference between the authenticated return, which shows the page url with the payments_intent value in the address bar, and non-authenticated, which only shows the page url. I presume the page relies on these values being available?

I'm not clear enough on the payment mechanism. Do you know what triggers 'perch_shop_order_successful()'?

As I say, the payment is taken by Stripe, the order registers in every other meaningful way (appears in orders, sends email) in Perch except for the correct output of the result page.

If I remove the conditionals testing for perch_shop_order_successful(), it works fine.

Thank you again.

**Comment by byron-roots** [comment]
The `perch_shop_order_successful()` just checks the if the order `isPaid`. When the payment gateway takes the payment the order is then finalised as paid. This happens during the `perch_shop_confirm_payment()` method, which just sets the `orderStatus` to 'paid', you'll be able to verify this in the CMS.

When checking if the order `isPaid` this checks if the orderStatus is set to 'paid'. If the orders in the CMS is showing as paid, then I think the problem would be perch not being able to retrieve the current order when checking `perch_shop_order_successful()`. This could be an issue with sessions on the site, especially if it's intermittent and only happening on your live site and not during testing. 

The `perch_shop_confirm_payment()` method does rely on payments_intent query parameter when being redirected to complete the payment.

If you can test it out and get the output for the `$Order` Object that should explain things. This is how it is retrieved in the `perch_shop_order_successful()` method 
```
$ShopRuntime = PerchShop_Runtime::fetch();
$Order = $ShopRuntime->get_active_order();
```

Then if you print/dump out the `$Order` object or log it to the PerchDebug it should let us know the `orderStatus`.

**Comment by ghost** [comment]
That's great. Thank you so much. I'll give it all a whirl.
