### ISSUE TITLE
/result (complete) page not fully rendering when 3d secrure card used

### ISSUE THREAD

**Issue by ndwl** [RootStudio/Root-Perch-Shop-Omnipay-v3#5]
gateway working and talking to stripe when a none secure card is used, however when a 3d secure card number is used stripe is contacted, the 3d Secure page appears and when authenticated is selected the user is returned to the results page however it doesn't fully render, any thoughts?

```
<?php					
if (PerchUtil::get('payment_intent')) {

    $payment_opts = [
        'paymentIntentReference' => PerchUtil::get('payment_intent'), // set the reference ID
        'returnUrl'              => '/result',
        'confirm'                => true, // We are confirming the payment so we want this true
    ];

    // New method to confirm the payment. Use the above options and the new intents gateway
    perch_shop_confirm_payment('stripe_intents', $payment_opts);
}
									
// Has the order been succcessfully placed?
if (perch_shop_order_successful()) {

	perch_shop_empty_cart();
	
    // Yes! Show a success message
	perch_content('Success heading');
    perch_content('Order successful');

}else{

    // Payment problem! Show instructions to the customer
	perch_content('Failiure heading');
    perch_content('Payment not successful');
}
?>
```

**Comment by byron-roots** [comment]
Are you using relative or absolute urls? if you are using relative URLs try updating these to absolute.

Are you getting any errors in your logs? If the page isn't fully rendered sounds like a php error is preventing the rest of the page from being processed

**Comment by ndwl** [comment]
Thanks Byron, seems to ahve vdone the trick. D o you know how to pass the billing address info to stripe. do my ids have to match theirs?

**Comment by byron-roots** [comment]
When calling the payment method from stripe there are several options you can add, one being the billing details. You can see them all in [their docs](https://stripe.com/docs/api/payment_methods/create). 

In my example I get the billing details from the form as follows

```
const address = document.querySelector( '[name="address"]' );
const city = document.querySelector( '[name="city"]' );
const postcode = document.querySelector( '[name="postcode"]' );
```
You can get the field any way you like, and can add additional fields if you want as well. If the field is optional make sure to check how an empty field interacts with stripe. 

The object keys you pass to stripe must match their keys from their docs. As stripe are an American company they use state, but this can take the value of a county, or the countries equivalent.
```
this.stripe.createPaymentMethod( 'card', this.cardElement, {
                        billing_details: {
                            name: cardholderName.value,
                            email: email.value,
                            address: {
                                line1: address.value,
                                postal_code: postcode.value,
                                city: city.value,
                                country: 'GB'
                            }
                        }
```
